language: php
sudo: false
php:
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - "5.3"
  - "hhvm"
env:
  - DISABLE_FUNCTIONS=
  - DISABLE_FUNCTIONS="gzopen"
matrix:
  allow_failures:
    - php: "7.0"
    - php: "hhvm"
notifications:
  slack: hozong:haBs33ICo44odrx7iM01nBvg
services:
  - "mysql"
  - "postgresql"
before_script:
  - echo "disable_functions=$DISABLE_FUNCTIONS" >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini
  - cp _test/mysql.conf.php.dist _test/mysql.conf.php
  - cp _test/pgsql.conf.php.dist _test/pgsql.conf.php
script: cd _test && phpunit --verbose --stderr
